-- Seed data migrated from the Google Sheet on 2026-08-03 (99 goals).
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Win a game with your commander never leaving the command zone.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 10 or more lands at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Attack with five or more creatures at the same time.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a permanent of each color (WUBRG) at the same time.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Gain 30 or more life in a single game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Have 10 or more cards in your hand at any point', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 5 or more token creatures at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Draw 5 or more cards from a single spell or ability.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a spell with mana value 10 or greater.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Deal 20 or more combat damage to a single opponent in one combat.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 3 or more planeswalkers at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a creature with 10 or more +1/+1 counters on it.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast four or more spells in a single turn.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 20 or more permanents at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a spell with an X in its mana cost with X of 8 or greater.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a creature enchanted or equipped by 3 or more Auras/Equipment.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Win a game where you were at 10 or fewer life at some point during it.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Have every creature you control share a single creature type (minimum 5 creatures).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Win a game as the last player still holding cards in hand (all opponents hellbent at the finish).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a creature with power 10 or greater.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 5 or more artifacts at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 5 or more enchantments at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 3 or more creatures with power 5 or greater at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Deal combat damage to each opponent in a single combat.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a creature that has both flying and trample.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control an Equipment attached to a creature and an Aura attached to a creature at the same time.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Win a game in which your commander dealt no combat damage the entire game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Deal the first combat damage to a player in the game ("first blood").', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Become the monarch.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a spell from exile (foretell, adventure, cast-from-exile effect, or an exiled card).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a spell with an alternative cost', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Have a spell you cast trigger cascade, and cast the cascaded spell.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Put a nonland permanent onto the battlefield without casting it.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Reanimate a creature card from any graveyard (return it to the battlefield from a graveyard).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Have 20 or more cards in your graveyard at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Mill yourself 5 or more cards at once from a single spell or effecg', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a spell during each of your first three turns of the game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Have 5 or more devotion to a single color (count colored pips on your permanents).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a creature with menace, or with an evasion keyword, that deals combat damage unblocked.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a creature and give it haste, then attack with it the same turn it entered.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a spell with flashback, escape, disturb, or a similar keyword that casts it from your graveyard.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Sacrifice three or more permanents in a single turn (to any costs or abilities).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Win a coin flip or die roll for an in-game effect (a card made you flip/roll, and you got the good result).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Goad a creature (force it to attack).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Give an opponent something beneficial via one of your cards ‚a cards, mana, life, or a token ("group hug" gift).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Get a creature through unblocked using an obscure evasion keyword: horsemanship, shadow, fear, or intimidate.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a nontoken clone that copies another creature on the battlefield (a permanent with the same name as something else in play).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Proliferate.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control a permanent of each color, a token, a planeswalker, and 10+ lands all at the same time.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Attack with ten or more creatures at the same time.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control a creature with power 40 or greater.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Reduce a single opponent from 40 life to 0 in one turn through combat damage only.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control 30 or more permanents at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Earn points from at least one 1-point and one 2-point goal in the same league night.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Be the monarch at the beginning of your end step (successfully drawing the monarch card) in three separate turns of one game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Steal the monarch from another player via combat damage.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Have 10 or more devotion to a single color at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Have more cards in your graveyard than in your library at the end of a turn.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Reanimate an opponent''s creature and attack with it.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control 15 or more lands at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Cast three or more spells from exile in a single game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Return five or more permanents from graveyards to the battlefield over one game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Win a game in which you were the monarch at the moment of victory.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Eliminate two players in the same turn.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Cast a spell with an X in its mana cost with X of 12 or greater.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Deal combat damage to all opponents in a single combat', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Have 60 or more life at any point in a game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control 5 or more permanents with counters on them at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Cast a spell that forces every player to do the same thing symmetrically (mass chaos / group effect ‚ e.g. everyone draws, everyone sacrifices, everyone shuffles in and redraws).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Ninjutsu a creature into play (return an unblocked attacker and put a Ninja onto the battlefield attacking), or otherwise swap an attacker for another creature mid-combat.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control one of each "artifact-with-a-purpose" token at the same time: a Treasure, a Clue, and a Food (minimum three different named token types).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Resolve a vote (a "will of the council" / "council''s dilemma" card where players vote), regardless of the outcome.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control a creature with three or more different keyword abilities on it at once (printed or granted).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Control the only nonland permanent on the battlefield at the end of a turn (every other player''s board is empty of nonland permanents ‚ "the cheese stands alone").', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Win a game in which every creature you controlled at the moment of victory was a token.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Control, at the same time, at least one creature with each of these five keywords across your board: flying, trample, deathtouch, lifelink, and vigilance.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Win a game in which you never attacked with a creature the entire game.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Win a game the turn after being at 5 or fewer life at the start of that turn.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Control five permanents that each tap for one distinct color of WUBRG (all five colors represented).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Control 10 or more legendary permanents at once.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Win a game in which, at the moment of victory, you controlled zero lands.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Win a game while at exactly 1 life.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Win a game in which the winning damage or effect came from an opponent''s own permanent that you controlled or redirected.', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Win a game on an opponent''s turn (you meet a win condition or deliver lethal during a turn that is not yours).', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control a Storied board state. Control a Legendary Artifact, Legendary Creature, and Saga at the same time', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 5 or more Halfling creatures (Changelings don''t count)', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Control 5 or more Dwarf creatures (Changelings don''t count)', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Go on 3 or more Adventures (cast three adventure type spells)', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (3, 'Master of Stories. Control 5 or more sagas at once', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'As foretold... Attach a LOTR/Hobbit equipment to the appropriate character (Sting to Bilbo/Frodo/Sam, Orcrist to Thorin, Wizard''s Staff to Gandalf, etc)', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Create a horde.. Control 10 or more Treasures', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'There and back again... Cast an adventure spell and then later cast it out of exile as a permanent', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (2, 'Throw it into the fire... Exile or Destroy a non-token Legendary Artifact you control', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Battle of five armies... in a single combat phase, attack with five creatures who share no creature types with each other', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Assemble a host... control 10 or more non-token creatures who share a Creature Type', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Recruitment Center... control 20 or more 1/1 token creatures', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Arrive Precisely When You Mean To... Cast your commander for the first time on Turn 1 or Turn 6', 'Hobbit');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Cast a spell with the same name 5+ times (ex. prepared spells, recursion, hare apparent type effects)', '');
INSERT INTO points_deck (pts, goal, set_name) VALUES (1, 'Army of Darkness... Control an Army with 5 or more counters on it.', '');
